### ISSUE TITLE
Migrate to scoped package

### ISSUE THREAD

**Issue by timkurvers** [wowserhq/math#26]
Should we start scoping our packages to the `wowserhq` org on npm?

From https://docs.npmjs.com/files/package.json#name:

> A name can be optionally prefixed by a scope, e.g. `@myorg/mypackage`.

Consumers would then write:

```js
import { Matrix4 } '@wowserhq/wowser-math'
```

More information here: https://docs.npmjs.com/misc/scope

**Comment by timkurvers** [comment]
I'm actually a bit unsure how `wowser-math` and `eslint-config-wowser-base` have ended up on the organization page on npm: https://www.npmjs.com/org/wowserhq/

Any thoughts @fallenoak?

**Comment by fallenoak** [comment]
@timkurvers I added them manually.

**Comment by timkurvers** [comment]
Ah I see, that makes sense. Should we continue doing that or use the org scope?

**Comment by fallenoak** [comment]
Per our recent discussions, I'm modifying this issue to cover migrating `wowser-math` to `@wowserhq/math`.

**Comment by timkurvers** [comment]
👍

**Comment by fallenoak** [comment]
I've published a scoped package under `@wowserhq/math` and updated the repo name to reflect our new convention. Closing!
